builder:
  track: dev

labels:
  type: web
  app-group: ziplinee-ci
  team: ziplinee-team
  language: nodejs

version:
  semver:
    major: 1
    minor: 0
    patch: 0

stages:
  audit-and-restore:
    parallelStages:
      audit:
        image: extensions/npm-audit:dev
        action: audit
        level: low
        dev-level: critical
        workspace: ziplinee
        channels:
        - '#npm-audit'

      restore:
        image: node:16-alpine
        env:
          npm_config_update-notifier: false
        commands:
        - npm ci

  lint-and-build:
    parallelStages:
      lint:
        image: node:16-alpine
        env:
          npm_config_update-notifier: false
        commands:
        - npm run lint

      build:
        image: node:16-alpine
        env:
          npm_config_update-notifier: false
        commands:
        - npm run build

  bake:
    image: extensions/docker:dev
    action: build
    severity: unknown
    repositories:
    - ziplineeci
    path: ./dist
    copy:
    - favicon.ico
    - nginx.vh.default.conf
    - docker-entrypoint.sh
    - package-lock.json

  test:
    services:
    - name: ci.ziplineeci.io
      image: ziplineeci/ziplinee-ci-web:${ZIPLINEE_BUILD_VERSION}
      readiness:
        path: /robots.txt
        port: 5000

    image: node:16-alpine
    env:
      npm_config_update-notifier: false
    commands:
    - apk add curl
    - curl --fail http://ci.ziplineeci.io:5000/manifest/encrypt

  push-to-docker-hub:
    image: extensions/docker:dev
    retries: 5
    action: push
    repositories:
    - ziplineeci

  tag-revision:
    image: bitnami/git
    commands:
    - git tag ${ZIPLINEE_BUILD_VERSION}
    - git push origin ${ZIPLINEE_BUILD_VERSION}
    when: status == 'succeeded' && branch == 'main'

#  slack-notify:
#    image: extensions/slack-build-status:dev
#    workspace: ziplinee
#    channels:
#    - '#build-status'
#    when:
#      status == 'succeeded' ||
#      status == 'failed'
